"""
Citizen Advisory Agent — a DETERMINISTIC CPCB health-guidance lookup wrapped in
an LLM narrative layer for multilingual, voice-ready citizen advisories.

TRUST MODEL (why this is split in two)
--------------------------------------
The health facts come from a hardcoded table sourced from CPCB's published AQI
health-impact guidance (`HEALTH_GUIDANCE`) — analogous to AgriBloom's DISCLAIMERS
dict. This is the ground truth the citizen relies on, so it is NEVER generated by
an LLM: the model cannot hallucinate a wrong "it's safe to jog" for a Severe day.
The LLM's only job is to *rephrase and localize* that fixed guidance into a
short, friendly advisory in the requested language — it is explicitly forbidden
from inventing AQI numbers or health claims. If no LLM is configured (or the call
fails), we fall back to the deterministic guidance text directly, so the endpoint
always returns real, safe advice.

LANGUAGE HANDLING
-----------------
We ask the LLM to respond *directly* in the requested language (single call),
rather than generating English and translating after — simpler and avoids a
second round-trip / a second place for errors to creep in. The deterministic
fallback ships hardcoded English + Hindi guidance; other languages (e.g. Kannada)
are only available via the LLM path and fall back to English guidance text
otherwise (clearly noted in the advisory).

SOURCE CITATION (trust-transparency, informed by the Drishti submission)
------------------------------------------------------------------------
Every advisory returns `sources_cited` with the exact station id/name, the
reading timestamp, and the AQI value/category it was based on — so a citizen (or
an auditor) can trace the advice back to a real reading.
"""
from __future__ import annotations

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from agents.forecast_agent import AQI_CATEGORIES
from data.ingest._geo_utils import haversine_km

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
UNIFIED_PATH = ROOT / "data" / "db" / "unified_history.parquet"
ADVISORY_AUDIO_DIR = ROOT / "data" / "db" / "advisories"

# LLM narration is provider-flexible. The provider is auto-detected from the key
# (gsk_… → Groq, sk-ant-api… → Anthropic) unless LLM_PROVIDER is set, and every
# default is overridable via env (LLM_PROVIDER / LLM_MODEL / LLM_BASE_URL).
# Groq and any OpenAI-compatible endpoint go over HTTP; Anthropic uses its SDK.
_PROVIDER_DEFAULTS = {
    "groq": {"base_url": "https://api.groq.com/openai/v1", "model": "llama-3.3-70b-versatile"},
    "openai": {"base_url": "https://api.openai.com/v1", "model": "gpt-4o-mini"},
    "anthropic": {"base_url": None, "model": "claude-opus-4-8"},
}
SECOND_LANGUAGE = "hi"  # deterministic fallback covers en + hi; others need the LLM
GTTS_LANGS = {"en": "en", "hi": "hi", "kn": "kn"}

# Localised CPCB category labels for the deterministic (no-LLM) fallback.
CATEGORY_LABELS = {
    "en": {"good": "good", "satisfactory": "satisfactory", "moderate": "moderate",
           "poor": "poor", "very_poor": "very poor", "severe": "severe"},
    "hi": {"good": "अच्छी", "satisfactory": "संतोषजनक", "moderate": "मध्यम",
           "poor": "खराब", "very_poor": "बहुत खराब", "severe": "गंभीर"},
}

# --- CPCB AQI category health guidance (deterministic ground truth) -----------
# Sourced from CPCB's published National Air Quality Index health-impact
# statements. NOT LLM-generated. Keys: category -> {general, sensitive}.
# `en` is authoritative; `hi` is a hand-translated mirror for the offline path.
HEALTH_GUIDANCE: dict[str, dict[str, dict[str, str]]] = {
    "en": {
        "good": {
            "general": "Air quality is good. It's a great day to be outdoors and active.",
            "sensitive": "No precautions needed, even for children, the elderly, or people with heart or lung conditions.",
        },
        "satisfactory": {
            "general": "Air quality is satisfactory. Outdoor activity is fine for most people.",
            "sensitive": "Unusually sensitive people may feel minor breathing discomfort; take it easy if you notice it.",
        },
        "moderate": {
            "general": "Air quality is moderate. Most people can continue normal activity.",
            "sensitive": "People with asthma, heart disease, children, and older adults may feel breathing discomfort — reduce prolonged or heavy outdoor exertion.",
        },
        "poor": {
            "general": "Air quality is poor. Cut back on prolonged or strenuous outdoor activity.",
            "sensitive": "People with heart or lung disease, children, and older adults should avoid outdoor exertion and consider a mask (N95) outdoors.",
        },
        "very_poor": {
            "general": "Air quality is very poor. Avoid outdoor exercise and keep windows closed; wear an N95 mask outside.",
            "sensitive": "People with heart or lung disease, children, and older adults should stay indoors and use an air purifier if available; seek care if you have breathing difficulty.",
        },
        "severe": {
            "general": "Air quality is severe — hazardous to everyone. Stay indoors, keep windows shut, and avoid all outdoor exertion; wear an N95 mask if you must go out.",
            "sensitive": "People with heart or lung disease, children, and older adults are at serious risk — remain indoors, run an air purifier, and seek medical help for any breathing difficulty.",
        },
    },
    "hi": {
        "good": {
            "general": "वायु गुणवत्ता अच्छी है। बाहर घूमने और सक्रिय रहने के लिए बढ़िया दिन है।",
            "sensitive": "बच्चों, बुज़ुर्गों या हृदय/फेफड़े के रोगियों के लिए भी किसी सावधानी की ज़रूरत नहीं है।",
        },
        "satisfactory": {
            "general": "वायु गुणवत्ता संतोषजनक है। अधिकांश लोगों के लिए बाहरी गतिविधि ठीक है।",
            "sensitive": "बहुत संवेदनशील लोगों को हल्की साँस की तकलीफ़ हो सकती है; महसूस होने पर आराम करें।",
        },
        "moderate": {
            "general": "वायु गुणवत्ता मध्यम है। अधिकांश लोग सामान्य गतिविधि जारी रख सकते हैं।",
            "sensitive": "दमा, हृदय रोग वाले लोग, बच्चे और बुज़ुर्ग साँस की तकलीफ़ महसूस कर सकते हैं — लंबे या भारी बाहरी परिश्रम से बचें।",
        },
        "poor": {
            "general": "वायु गुणवत्ता खराब है। लंबे या कठिन बाहरी परिश्रम को कम करें।",
            "sensitive": "हृदय/फेफड़े के रोगी, बच्चे और बुज़ुर्ग बाहरी परिश्रम से बचें और बाहर N95 मास्क पहनें।",
        },
        "very_poor": {
            "general": "वायु गुणवत्ता बहुत खराब है। बाहरी व्यायाम से बचें, खिड़कियाँ बंद रखें और बाहर N95 मास्क पहनें।",
            "sensitive": "हृदय/फेफड़े के रोगी, बच्चे और बुज़ुर्ग घर के अंदर रहें, हो सके तो एयर प्यूरीफायर चलाएँ; साँस लेने में दिक्कत हो तो डॉक्टर से मिलें।",
        },
        "severe": {
            "general": "वायु गुणवत्ता गंभीर है — सभी के लिए हानिकारक। घर के अंदर रहें, खिड़कियाँ बंद रखें, बाहरी परिश्रम से बचें; बाहर जाना ज़रूरी हो तो N95 मास्क पहनें।",
            "sensitive": "हृदय/फेफड़े के रोगी, बच्चे और बुज़ुर्ग गंभीर जोखिम में हैं — घर के अंदर रहें, एयर प्यूरीफायर चलाएँ और साँस की किसी भी तकलीफ़ पर तुरंत चिकित्सा सहायता लें।",
        },
    },
}


# --- helpers -----------------------------------------------------------------


def aqi_category_name(aqi: float | None) -> str | None:
    """Map an AQI value to its CPCB category name (good..severe)."""
    if aqi is None:
        return None
    for name, (_lo, hi) in AQI_CATEGORIES.items():
        if aqi <= hi:
            return name
    return list(AQI_CATEGORIES)[-1]  # above the top breakpoint → severe


def _nearest_station_reading(city: str, lat: float | None, lon: float | None,
                             station_id: str | None) -> dict | None:
    """Latest observed AQI + station identity for `city`, matched by station_id or
    nearest coordinates. Used when the caller doesn't supply a forecast."""
    if not UNIFIED_PATH.exists():
        return None
    u = pd.read_parquet(UNIFIED_PATH, columns=["city", "station_id", "station_name", "lat", "lon", "timestamp", "aqi"])
    u = u[(u["city"] == city)].dropna(subset=["lat", "lon", "aqi", "timestamp"])
    if u.empty:
        return None
    u = u.sort_values("timestamp")
    latest = u.groupby("station_id").tail(1)
    if station_id and (latest["station_id"] == station_id).any():
        row = latest[latest["station_id"] == station_id].iloc[0]
    elif lat is not None and lon is not None:
        latest = latest.assign(_d=latest.apply(lambda r: haversine_km(lat, lon, r["lat"], r["lon"]), axis=1))
        row = latest.sort_values("_d").iloc[0]
    else:
        row = latest.iloc[-1]
    return {
        "station_id": row["station_id"],
        "station_name": row.get("station_name") or row["station_id"],
        "lat": float(row["lat"]),
        "lon": float(row["lon"]),
        "aqi": float(row["aqi"]),
        "timestamp": pd.to_datetime(row["timestamp"]).isoformat(),
        "source": "observed",
    }


def _resolve_reading(state: dict[str, Any]) -> dict | None:
    """Decide what AQI reading the advisory is about.

    Prefers the Forecast Agent's output in `state["forecast"]`; otherwise falls
    back to the latest observed reading for the point/station.
    """
    forecast = state.get("forecast") or {}
    aqi = None
    for k in ("aqi", "predicted_aqi", "forecast_aqi", "value"):
        if isinstance(forecast, dict) and forecast.get(k) is not None:
            aqi = float(forecast[k])
            break
    if aqi is not None:
        return {
            "station_id": state.get("station_id") or forecast.get("station_id"),
            "station_name": state.get("station_name") or forecast.get("station_name")
            or state.get("station_id") or forecast.get("station_id") or f"{state.get('city')} station",
            "lat": state.get("lat") if state.get("lat") is not None else forecast.get("lat"),
            "lon": state.get("lon") if state.get("lon") is not None else forecast.get("lon"),
            "aqi": aqi,
            "timestamp": forecast.get("timestamp") or forecast.get("valid_at")
            or datetime.now(timezone.utc).isoformat(),
            "source": f"forecast{'+' + str(forecast.get('horizon_hours')) + 'h' if forecast.get('horizon_hours') else ''}",
        }
    # No forecast supplied → use the latest observed reading.
    return _nearest_station_reading(state.get("city"), state.get("lat"), state.get("lon"), state.get("station_id"))


# --- LLM narrative layer (provider-swappable) --------------------------------


def _detect_provider(key: str) -> str:
    """Auto-detect the LLM provider from LLM_PROVIDER or the key prefix."""
    forced = os.getenv("LLM_PROVIDER", "").strip().lower()
    if forced:
        return forced
    if key.startswith("sk-ant-"):
        return "anthropic"
    if key.startswith("gsk_"):
        return "groq"
    # OpenAI keys start with sk-; anything else we treat as an OpenAI-compatible
    # endpoint (Groq is the default base URL) — override with LLM_BASE_URL.
    return "openai" if key.startswith("sk-") else "groq"


def call_llm(prompt: str, system: str | None = None, max_tokens: int = 400) -> str | None:
    """
    Single, provider-flexible LLM call. Reads the key from LLM_API_KEY and routes
    to whichever provider is present (auto-detected, or forced via LLM_PROVIDER):
    Anthropic (Claude SDK) or any OpenAI-compatible /chat/completions endpoint
    (Groq by default, also OpenAI/OpenRouter/Together via LLM_BASE_URL). Returns
    the response text, or None if no key / the call fails — callers fall back to
    the deterministic guidance.
    """
    key = os.getenv("LLM_API_KEY", "").strip()
    if not key:
        logger.info("LLM_API_KEY not set — using deterministic advisory (no LLM narration).")
        return None
    provider = _detect_provider(key)
    if provider == "anthropic":
        return _call_anthropic(key, prompt, system, max_tokens)
    return _call_openai_compatible(provider, key, prompt, system, max_tokens)


def _call_anthropic(key: str, prompt: str, system: str | None, max_tokens: int) -> str | None:
    try:
        import anthropic
    except ImportError:
        logger.warning("anthropic SDK not installed — falling back to deterministic advisory.")
        return None
    model = os.getenv("LLM_MODEL", "").strip() or _PROVIDER_DEFAULTS["anthropic"]["model"]
    try:
        client = anthropic.Anthropic(api_key=key)
        resp = client.messages.create(
            model=model, max_tokens=max_tokens, system=system,
            messages=[{"role": "user", "content": prompt}],
        )
        return "".join(b.text for b in resp.content if getattr(b, "type", None) == "text").strip() or None
    except Exception as exc:  # network/auth/etc. — never let the advisory hard-fail
        logger.warning(f"Anthropic LLM call failed ({exc}); falling back to deterministic advisory.")
        return None


def _call_openai_compatible(provider: str, key: str, prompt: str, system: str | None, max_tokens: int) -> str | None:
    """Groq / OpenAI / any OpenAI-compatible chat-completions endpoint, over HTTP."""
    import requests

    defaults = _PROVIDER_DEFAULTS.get(provider, _PROVIDER_DEFAULTS["groq"])
    base = (os.getenv("LLM_BASE_URL", "").strip() or defaults["base_url"]).rstrip("/")
    model = os.getenv("LLM_MODEL", "").strip() or defaults["model"]
    messages = ([{"role": "system", "content": system}] if system else []) + [{"role": "user", "content": prompt}]
    try:
        r = requests.post(
            f"{base}/chat/completions",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={"model": model, "messages": messages, "max_tokens": max_tokens, "temperature": 0.3},
            timeout=30,
        )
        if r.status_code >= 400:
            logger.warning(f"{provider} LLM HTTP {r.status_code}: {r.text[:200]} — falling back to deterministic advisory.")
            return None
        content = (r.json()["choices"][0]["message"]["content"] or "").strip()
        return content or None
    except Exception as exc:
        logger.warning(f"{provider} LLM call failed ({exc}); falling back to deterministic advisory.")
        return None


def _guidance_for(category: str, lang: str) -> tuple[dict[str, str], str]:
    """Return (guidance dict, guidance_lang) for a category, falling back to English."""
    table = HEALTH_GUIDANCE.get(lang) or HEALTH_GUIDANCE["en"]
    guidance = table.get(category) or HEALTH_GUIDANCE["en"].get(category)
    guidance_lang = lang if (lang in HEALTH_GUIDANCE and category in HEALTH_GUIDANCE[lang]) else "en"
    return guidance, guidance_lang


def _build_prompt(city: str, category: str, aqi: float, guidance: dict[str, str],
                  reading: dict, lang: str, attribution: dict | None) -> tuple[str, str]:
    src_line = ""
    if attribution and attribution.get("overall_source_estimate") not in (None, "indeterminate"):
        src_line = (
            f"- Likely dominant local pollution source (correlational estimate): "
            f"{attribution['overall_source_estimate']}.\n"
        )
    system = (
        "You are a public-health communicator for an Indian city air-quality service. "
        "You ONLY rephrase and localize the health guidance you are given. "
        "Do NOT invent AQI numbers, categories, or health claims that are not in the provided context. "
        "Keep it to 2-3 short, friendly, actionable sentences."
    )
    prompt = (
        f"Write a citizen air-quality advisory in language code '{lang}'. Respond ONLY with the "
        f"advisory text in that language, no preamble.\n\n"
        f"GROUND TRUTH (do not contradict or add to the health facts):\n"
        f"- City: {city}\n"
        f"- Monitoring station: {reading['station_name']}\n"
        f"- Reading time: {reading['timestamp']} ({reading['source']})\n"
        f"- AQI: {aqi:.0f} — category '{category}'\n"
        f"- Guidance for the general public: {guidance['general']}\n"
        f"- Guidance for sensitive groups (children, elderly, heart/lung patients): {guidance['sensitive']}\n"
        f"{src_line}"
        f"\nMention the station name and that the reading is for {city}. Be warm and practical."
    )
    return prompt, system


def _deterministic_advisory(city: str, category: str, aqi: float, guidance: dict[str, str],
                            guidance_lang: str, reading: dict, lang: str) -> str:
    """Compose an advisory purely from the hardcoded guidance (no LLM)."""
    note = ""
    if lang != guidance_lang:
        note = f" (Guidance shown in English; '{lang}' narration requires the LLM service.)"
    if guidance_lang == "hi":
        label = CATEGORY_LABELS["hi"].get(category, category)
        return (
            f"{reading['station_name']} ({city}) पर AQI {aqi:.0f} है — '{label}'। "
            f"{guidance['general']} {guidance['sensitive']}"
        )
    label = CATEGORY_LABELS["en"].get(category, category.replace("_", " "))
    return (
        f"At {reading['station_name']} in {city}, the AQI is {aqi:.0f} — '{label}'. "
        f"{guidance['general']} {guidance['sensitive']}{note}"
    )


# --- optional TTS ------------------------------------------------------------


def _maybe_generate_tts(text: str, lang: str, station_id: str | None) -> str | None:
    if not os.getenv("TTS_ENABLED", "").strip():
        return None
    try:
        from gtts import gTTS
    except ImportError:
        logger.warning("TTS_ENABLED set but gTTS not installed — skipping audio.")
        return None
    try:
        ADVISORY_AUDIO_DIR.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        safe_station = str(station_id or "station").replace("/", "_")
        out = ADVISORY_AUDIO_DIR / f"advisory_{safe_station}_{lang}_{stamp}.mp3"
        gTTS(text=text, lang=GTTS_LANGS.get(lang, "en")).save(str(out))
        return str(out)
    except Exception as exc:
        logger.warning(f"TTS generation failed ({exc}); returning advisory without audio.")
        return None


# --- LangGraph node ----------------------------------------------------------


def run_advisory(state: dict[str, Any]) -> dict[str, Any]:
    """Produce a localized, source-cited citizen advisory. See module docstring.

    Input state: city, (lat & lon) or station_id, lang (default 'en'),
                 forecast (from Forecast Agent), attribution (optional).
    Output state: advisory_text, voice_output_path (optional), sources_cited, status.
    """
    city = state.get("city")
    lang = (state.get("lang") or "en").strip().lower()
    if not city:
        state["status"] = "error"
        state["error"] = "missing city"
        return state

    reading = _resolve_reading(state)
    if reading is None or reading.get("aqi") is None:
        state["status"] = "error"
        state["error"] = "no forecast provided and no observed AQI available for this city/point"
        return state

    aqi = reading["aqi"]
    category = (state.get("forecast") or {}).get("category") or aqi_category_name(aqi)
    guidance, guidance_lang = _guidance_for(category, lang)
    attribution = state.get("attribution")

    prompt, system = _build_prompt(city, category, aqi, guidance, reading, lang, attribution)
    llm_text = call_llm(prompt, system=system)
    if llm_text:
        advisory_text = llm_text
        narration = "llm"
    else:
        advisory_text = _deterministic_advisory(city, category, aqi, guidance, guidance_lang, reading, lang)
        narration = "deterministic_fallback"

    voice_output_path = _maybe_generate_tts(advisory_text, lang, reading.get("station_id"))

    state["advisory_text"] = advisory_text
    state["voice_output_path"] = voice_output_path
    state["sources_cited"] = {
        "station_id": reading.get("station_id"),
        "station_name": reading.get("station_name"),
        "lat": reading.get("lat"),
        "lon": reading.get("lon"),
        "reading_timestamp": reading.get("timestamp"),
        "aqi": round(aqi, 1),
        "aqi_category": category,
        "reading_source": reading.get("source"),
        "guidance_source": "CPCB National AQI health-impact guidance (deterministic table)",
        "narration": narration,
        "language": lang,
    }
    state["status"] = "ok"
    return state


__all__ = ["run_advisory", "call_llm", "aqi_category_name", "HEALTH_GUIDANCE"]
